QTJOLIE_INCDIR = @INCLUDE_INSTALL_DIR@
QTJOLIE_LIBDIR = @LIB_INSTALL_DIR@

CONFIG *= qt
INCLUDEPATH += $$QTJOLIE_INCDIR
LIBS += -L$$QTJOLIE_LIBDIR

LINKAGE = -lQtJolie
CONFIG(debug, debug|release) {
	windows:LINKAGE = -lQtJolied
	mac:LINKAGE = -lQtJolie_debug
}
LIBS += $$LINKAGE
