{
    "KPlugin": {
        "Authors": [
            {
                "Email": "kde-artists@kde.org",
                "Name": "KDE Visual Design Group"
            }
        ],
        "Category": "",
        "Description": "Breeze Dark by the KDE VDG",
        "Description[ar]": "نسيم داكن من من مجموعة تصميم كدي",
        "Description[az]": "KDE VDG tərəfindən Tünd Breeze",
        "Description[ca@valencia]": "Brisa fosca, creat pel VDG de KDE",
        "Description[ca]": "Brisa fosca, creat pel VDG del KDE",
        "Description[cs]": "Breeze Dark od KDE VDG",
        "Description[da]": "Breeze Dark af KDE VDG",
        "Description[de]": "Breeze-Dunkel von der KDE VDG",
        "Description[en_GB]": "Breeze Dark by the KDE VDG",
        "Description[es]": "Brisa oscuro por KDE VDG",
        "Description[et]": "Breeze tume KDE VDG-lt",
        "Description[eu]": "Breeze iluna, KDE VDGk egina",
        "Description[fi]": "Breeze Dark KDE VDG:ltä",
        "Description[fr]": "Breeze sombre, par KDE VDG",
        "Description[gl]": "Breeze escuro de KDE VDG",
        "Description[hu]": "Breeze Dark a KDE VDG-től",
        "Description[ia]": "Breeze Dark (Brisa Obscure) per le KDE VDG",
        "Description[id]": "Breeze Gelap oleh KDE VDG",
        "Description[it]": "Brezza scuro del KDE VDG",
        "Description[ko]": "KDE 시각 디자인 그룹에서 제작한 어두운 Breeze",
        "Description[nl]": "Breeze Dark door de KDE VDG",
        "Description[nn]": "Breeze mørk frå KDE VDG",
        "Description[pa]": "ਕੇਡੀਈ ਵੀਡੀਜੀ ਵਲੋਂ ਬਰੀਜ਼ ਗੂੜ੍ਹਾ",
        "Description[pl]": "Ciemna Bryza autorstwa KDE VDG",
        "Description[pt]": "Brisa Escuro da VDG do KDE",
        "Description[pt_BR]": "Breeze Dark pelo KDE VDG",
        "Description[ro]": "Briză, întunecat, de KDE VDG",
        "Description[ru]": "Тёмный вариант Breeze от KDE VDG",
        "Description[sk]": "Vánok Tmavý od KDE VDG",
        "Description[sl]": "Sapica temna (Breeze Dark) od KDE VDG",
        "Description[sv]": "Breeze mörk av KDE:s visuella designgrupp",
        "Description[tg]": "Насими торик аз KDE VDG",
        "Description[tr]": "KDE VDG tarafından yapılan Esinti Koyu",
        "Description[uk]": "Темна Breeze, автори — KDE VDG",
        "Description[vi]": "Breeze Tối, do KDE VDG",
        "Description[x-test]": "xxBreeze Dark by the KDE VDGxx",
        "Description[zh_CN]": "Breeze 微风深色主题，由 KDE VDG (视觉设计团队) 设计制作",
        "Description[zh_TW]": "由 KDE VDG 團隊製作的 Breeze Dark",
        "EnabledByDefault": true,
        "Id": "breeze-dark",
        "License": "LGPL",
        "Name": "Breeze Dark",
        "Name[ar]": "نسيم داكن",
        "Name[az]": "Breeze Tünd variant",
        "Name[ca@valencia]": "Brisa fosca",
        "Name[ca]": "Brisa fosca",
        "Name[cs]": "Breeze Tmavé",
        "Name[da]": "Breeze Dark",
        "Name[de]": "Breeze-Dunkel",
        "Name[en_GB]": "Breeze Dark",
        "Name[es]": "Brisa oscuro",
        "Name[et]": "Breeze tume",
        "Name[eu]": "Breeze iluna",
        "Name[fi]": "Breeze Dark",
        "Name[fr]": "Breeze sombre",
        "Name[gd]": "Dorch-oiteag",
        "Name[gl]": "Breeze escuro",
        "Name[hu]": "Breeze Dark",
        "Name[ia]": "Brisa obscure",
        "Name[id]": "Breeze Gelap",
        "Name[it]": "Brezza scuro",
        "Name[ko]": "어두운 Breeze",
        "Name[lt]": "Breeze tamsus",
        "Name[lv]": "Tumšā brīze",
        "Name[nb]": "Mørk bris",
        "Name[nds]": "Breeze düüster",
        "Name[nl]": "Breeze Dark",
        "Name[nn]": "Breeze mørk",
        "Name[pa]": "ਬਰੀਜ਼ ਗੂੜ੍ਹਾ",
        "Name[pl]": "Ciemna Bryza",
        "Name[pt]": "Brisa Escura",
        "Name[pt_BR]": "Breeze Dark",
        "Name[ro]": "Briză, întunecat",
        "Name[ru]": "Breeze, тёмный вариант",
        "Name[sk]": "Vánok Tmavý",
        "Name[sl]": "Sapica (temna)",
        "Name[sr@ijekavian]": "Поветарац тамни",
        "Name[sr@ijekavianlatin]": "Povetarac tamni",
        "Name[sr@latin]": "Povetarac tamni",
        "Name[sr]": "Поветарац тамни",
        "Name[sv]": "Breeze mörk",
        "Name[tg]": "Насими торик",
        "Name[tr]": "Esinti Koyu",
        "Name[uk]": "Темна Breeze",
        "Name[vi]": "Breeze Tối",
        "Name[x-test]": "xxBreeze Darkxx",
        "Name[zh_CN]": "Breeze 微风深色",
        "Name[zh_TW]": "Breeze Dark",
        "Version": "@KF_VERSION@",
        "Website": "https://plasma.kde.org"
    },
    "X-Plasma-API": "5.0"
}
