[Icon Theme]
Name=Unittest Theme two

DisplayDepth=32

DesktopDefault=48
DesktopSizes=16,22,32,48,64,128,256
ToolbarDefault=22
ToolbarSizes=16,22,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,32,48
SmallDefault=16
SmallSizes=16,22,32,48
PanelDefault=32
PanelSizes=16,22,32,48,64,128,256
DialogDefault=32
DialogSizes=16,22,32,48,64,128,256

########## Directories
########## ordered by category and alphabetically

Directories=apps/22

[apps/22]
Size=22
Context=Applications
Type=Fixed

