{
    "KPlugin": {
        "Authors": [
            {
                "Email": "kde-artists@kde.org",
                "Name": "KDE Visual Design Group"
            }
        ],
        "Category": "",
        "Description": "Breeze by the KDE VDG",
        "Description[ar]": "نسيم من مجموعة تصميم كدي",
        "Description[az]": "KDE VDG tərəfindən Breeze",
        "Description[ca@valencia]": "Brisa, creat pel VDG de KDE",
        "Description[ca]": "Brisa, creat pel VDG del KDE",
        "Description[cs]": "Breeze od KDE VDG",
        "Description[da]": "Breeze af KDE VDG",
        "Description[de]": "Breeze von der KDE VDG",
        "Description[en_GB]": "Breeze by the KDE VDG",
        "Description[es]": "Brisa por KDE VDG",
        "Description[et]": "Breeze KDE VDG-lt",
        "Description[eu]": "Breeze, KDE VDGk egina",
        "Description[fi]": "Breeze KDE VDG:ltä",
        "Description[fr]": "Breeze, par KDE VDG",
        "Description[gl]": "Breeze de KDE VDG",
        "Description[hu]": "Breeze a KDE VDG-től",
        "Description[ia]": "Breeze (Brisa) per le KDE VDG",
        "Description[id]": "Breeze oleh KDE VDG",
        "Description[it]": "Brezza del KDE VDG",
        "Description[ko]": "KDE 시각 디자인 그룹에서 제작한 Breeze",
        "Description[nl]": "Breeze door de KDE VDG",
        "Description[nn]": "Breeze frå KDE VDG",
        "Description[pl]": "Bryza autorstwa KDE VDG",
        "Description[pt]": "Brisa da VDG do KDE",
        "Description[pt_BR]": "Breeze pelo KDE VDG",
        "Description[ro]": "Briză, de KDE VDG",
        "Description[ru]": "Breeze от KDE VDG",
        "Description[sk]": "Vánok od KDE VDG",
        "Description[sl]": "Sapica (Breeze) od KDE VDG",
        "Description[sv]": "Breeze av KDE:s visuella designgrupp",
        "Description[tg]": "Насим аз KDE VDG",
        "Description[tr]": "KDE VDG tarafından yapılan Esinti",
        "Description[uk]": "Breeze, автори — KDE VDG",
        "Description[vi]": "Breeze, do KDE VDG",
        "Description[x-test]": "xxBreeze by the KDE VDGxx",
        "Description[zh_CN]": "Breeze 微风主题，由 KDE VDG (视觉设计团队) 设计制作",
        "Description[zh_TW]": "由 KDE VDG 團隊製作的 Breeze",
        "EnabledByDefault": true,
        "Id": "default",
        "License": "LGPL",
        "Name": "Breeze",
        "Name[ar]": "نسيم",
        "Name[az]": "Breeze",
        "Name[ca@valencia]": "Brisa",
        "Name[ca]": "Brisa",
        "Name[cs]": "Breeze",
        "Name[da]": "Breeze",
        "Name[de]": "Breeze",
        "Name[en_GB]": "Breeze",
        "Name[es]": "Brisa",
        "Name[et]": "Breeze",
        "Name[eu]": "Breeze",
        "Name[fi]": "Breeze",
        "Name[fr]": "Breeze",
        "Name[gd]": "Oiteag",
        "Name[gl]": "Breeze",
        "Name[hu]": "Breeze",
        "Name[ia]": "Brisa",
        "Name[id]": "Breeze",
        "Name[it]": "Brezza",
        "Name[ko]": "Breeze",
        "Name[lt]": "Breeze",
        "Name[lv]": "Brīze",
        "Name[nb]": "Bris",
        "Name[nds]": "Breeze",
        "Name[nl]": "Breeze",
        "Name[nn]": "Breeze",
        "Name[pa]": "ਬਰੀਜ਼",
        "Name[pl]": "Bryza",
        "Name[pt]": "Brisa",
        "Name[pt_BR]": "Breeze",
        "Name[ro]": "Briză",
        "Name[ru]": "Breeze",
        "Name[sk]": "Vánok",
        "Name[sl]": "Sapica",
        "Name[sr@ijekavian]": "Поветарац",
        "Name[sr@ijekavianlatin]": "Povetarac",
        "Name[sr@latin]": "Povetarac",
        "Name[sr]": "Поветарац",
        "Name[sv]": "Breeze",
        "Name[tg]": "Насим",
        "Name[tr]": "Esinti",
        "Name[uk]": "Breeze",
        "Name[vi]": "Breeze",
        "Name[x-test]": "xxBreezexx",
        "Name[zh_CN]": "Breeze 微风",
        "Name[zh_TW]": "Breeze",
        "Version": "@KF_VERSION@",
        "Website": "https://plasma.kde.org"
    },
    "X-Plasma-API": "5.0"
}
