{
    "KPlugin": {
        "Authors": [
            {
                "Email": "kde-artists@kde.org",
                "Name": "KDE Visual Design Group",
                "Name[az]": "KDE Vizual Dizayn Qrupu",
                "Name[ca@valencia]": "Grup de disseny visual de KDE",
                "Name[ca]": "Grup de disseny visual de KDE",
                "Name[es]": "El grupo de diseño visual de KDE",
                "Name[eu]": "KDE Diseinu bisualeko taldea",
                "Name[fr]": "Groupe de conception graphique de KDE « VDG » (Visual Design Group)",
                "Name[it]": "KDE Visual Design Group",
                "Name[nl]": "KDE Visuele ontwerpgroep",
                "Name[pt]": "Grupo de Desenho Visual do KDE",
                "Name[sl]": "Skupina vizualnega designa KDE",
                "Name[tr]": "KDE Görsel Tasarım Grubu",
                "Name[uk]": "Група з візуального дизайну KDE",
                "Name[vi]": "Đội Thiết kế Trực quan KDE",
                "Name[x-test]": "xxKDE Visual Design Groupxx",
                "Name[zh_CN]": "KDE 视觉设计团队"
            }
        ],
        "Category": "",
        "Description": "Breeze by the KDE VDG",
        "Description[az]": "KDE VDG tərəfindən Breeze İş mühiti görünüşü",
        "Description[ca@valencia]": "Brisa, creat pel VDG de KDE",
        "Description[ca]": "Brisa, creat pel VDG del KDE",
        "Description[es]": "Brisa por KDE VDG",
        "Description[eu]": "Brisa KDEren VDGk egina",
        "Description[fr]": "Breeze par l'équipe « KDE VDG »",
        "Description[it]": "Brezza a cura del KDE VDG",
        "Description[nl]": "Breeze door de KDE VDG",
        "Description[pt]": "Brisa da VDG do KDE",
        "Description[sl]": "Sapica od KDE VDG",
        "Description[tr]": "KDE VDG tarafından Esinti",
        "Description[uk]": "Breeze, автори — KDE VDG",
        "Description[vi]": "Breeze, do KDE VDG",
        "Description[x-test]": "xxBreeze by the KDE VDGxx",
        "Description[zh_CN]": "Breeze 微风主题，由 KDE VDG (视觉设计团队) 设计制作",
        "EnabledByDefault": true,
        "Id": "default",
        "License": "LGPL",
        "Name": "Breeze",
        "Name[az]": "Breeze",
        "Name[ca@valencia]": "Brisa",
        "Name[ca]": "Brisa",
        "Name[es]": "Brisa",
        "Name[eu]": "Brisa",
        "Name[fr]": "Breeze",
        "Name[it]": "Brezza",
        "Name[nl]": "Breeze",
        "Name[pt]": "Brisa",
        "Name[sl]": "Sapica",
        "Name[tr]": "Esinti",
        "Name[uk]": "Breeze",
        "Name[vi]": "Breeze",
        "Name[x-test]": "xxBreezexx",
        "Name[zh_CN]": "Breeze 微风",
        "Version": "@KF_VERSION@",
        "Website": "https://plasma.kde.org"
    },
    "X-Plasma-API": "5.0"
}
